name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vitest:
    runs-on: ubuntu-latest
    name: Run Vitest with Prisma

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: 08-Testing/03-Vitest
        run: npm install && npx prisma generate

      - name: Run Vitest
        working-directory: 08-Testing/03-Vitest
        run: npm run test

  integration-test:
    runs-on: ubuntu-latest
    name: Run Integration Tests with Docker Compose

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Ensure Docker Compose is available
        run: docker-compose version

      - name: Copy .env.example to .env
        run: cp ./08-Testing/04-Integration-Tests/.env.example ./08-Testing/04-Integration-Tests/.env

      - name: Run integration tests
        working-directory: 08-Testing/04-Integration-Tests
        run: npm run test:integration
