name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vitest:
    runs-on: ubuntu-latest
    name: Run Vitest with Prisma

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: 08-Testing/03-Vitest
        run: npm install && npx prisma generate

      - name: Run Vitest
        working-directory: 08-Testing/03-Vitest
        run: npm run test

  integration-test:
    runs-on: ubuntu-latest
    name: Run Integration Tests with Docker Compose

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Verify Docker Compose Installation
        run: docker-compose version

      - name: Copy .env.example to .env
        run: cp ./1-integration-test/.env.example ./1-integration-test/.env

      - name: Run integration tests
        working-directory: 1-integration-test
        run: npm run test:integration
